apiVersion: batch/v1
kind: CronJob
metadata:
  name: runner
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: runner
        spec:
          restartPolicy: Never
          containers:
            - name: node
              image: "{{ .Values.werf.image.runner }}"
              workingDir: /app
